### ISSUE TITLE
Listing the hashing secret on the command-line poses a security risk

### ISSUE THREAD

**Issue by ehuelsmann** [emsearcy/srs-milter#2]
Wanting to lock down my mail server's exposure to users with log-in rights, I decided to use the unix socket variant for starting the milter.

However, when reviewing the system, I noted that the hashing secret can simply be found on the command line by running 'ps aux', thereby making the system as open to logged in users as the inet-socket-using method is.

Would it be an option to implement a configuration file? That way, I can lock down the secret with filesystem permissions in /etc and access to the SRS rewriter socket in /var/spool/postfix/var/run/... with filesystem permissions as well.

**Comment by driskell** [comment]
Hi ehuelsmann

Did you find an alternative solution you could share?

I like the look of this over pfixtools as it's a full milter approach which appears the better approach than canonical rewriting.

If you know of something better it be could to know. If not and you would still like the config file approach (which I would want too) I will fork and implement it for us :-)

Thanks

Jason

**Comment by ehuelsmann** [comment]
Hi Jason,

On Sun, Jan 5, 2014 at 1:56 PM, driskell notifications@github.com wrote:

> Hi ehuelsmann
> 
> Did you find an alternative solution you could share?

Nope. I didn't, unfortunately.

> I like the look of this over pfixtools as it's a full milter approach
> which appears the better approach than canonical rewriting.
> 
> One reason I wanted this milter is because it was dead simple to install
> other milters on Debian and have it all work immediately. That's what I'm
> expecting here as well.
> 
> If you know of something better it be could to know. If not and you would
> still like the config file approach (which I would want too) I will fork
> and implement it for us :-)
> 
> Really, the config file is the only option I have found so far. If you are
> ready to fork and implement the config file, that'd be absolutely great!
> I'd like to help test and review your changes, if you want me to. I'd even
> help implement it, if I wasn't so short on time.
> 
> Thanks
> 
> It's me who should be thanking! Anyway, thanks for contacting me!

## 

Bye,

Erik.

http://efficito.com -- Hosted accounting and ERP.
Robust and Flexible. No vendor lock-in.

**Comment by emsearcy** [comment]
I can help review too, or accept a pull request.  I will try to keep the .spec file updated to reflect RPM packaging for a new config file.

As far as alternative ideas, what do you think about using a secrets file instead of adding a configuration file layer, similar to how pfix-srsd does it (first line encoding, additional lines additional decoding secrets)?  It might be easier to implement?  I like the config file option too.

https://github.com/Fruneau/pfixtools/blob/master/pfix-srsd/pfix-srsd.asciidoc

**Comment by emsearcy** [comment]
Closed by #3
